---
# k3s
k3s_version: v1.28.2+k3s1
systemd_dir: /etc/systemd/system
k3s_server_ip: "{{ hostvars[groups['aws'][0]]['ansible_host'] | default(groups['aws'][0]) }}"
k3s_server_args: >-
  --node-ip '{{ k3s_node_ip | default(ansible_host) }}'
  --node-name '{{ k3s_node_name | default(inventory_host) }}'
  --cluster-cidr '10.21.0.0/16'
  --service-cidr '10.22.0.0/16'
  --cluster-dns '10.22.0.53'
  {{ k3s_extra_server_args | default("") }}
k3s_agent_args: >-
  --node-ip '{{ k3s_node_ip | default(ansible_host) }}'
  --node-name '{{ k3s_node_name | default(inventory_host) }}'
  {{ k3s_extra_agent_args | default("") }}
