---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: virgo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virgo-backend
  template:
    metadata:
      labels:
        app: virgo-backend
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: virgo-backend
        image: cs5224virgo/virgo-backend
        ports:
        - containerPort: 7000
          name: web
        command: ["/app/virgo"]
        args: ["server", "--config=/etc/config/config.yaml"]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: virgo-backend-config
---
apiVersion: v1
kind: Service
metadata:
  name: virgo-backend
spec:
  selector:
    app: virgo-backend
  ports:
  - protocol: TCP
    port: 7000
    targetPort: 7000
    name: web
    nodePort: 30001
  # type: ClusterIP
  type: NodePort
  # externalTrafficPolicy: Local
