---
- name: Disable services
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  failed_when: false
  with_items:
    - k3s
    - k3s-node

- name: pkill -9 -f "k3s/data/[^/]+/bin/containerd-shim-runc"
  register: pkill_containerd_shim_runc
  command: pkill -9 -f "k3s/data/[^/]+/bin/containerd-shim-runc"
  changed_when: "pkill_containerd_shim_runc.rc == 0"
  failed_when: false

- name: Umount k3s filesystems
  include_tasks: umount_with_children.yml
  with_items:
    - /run/k3s
    - /var/lib/kubelet
    - /run/netns
    - /var/lib/rancher/k3s
  loop_control:
    loop_var: mounted_fs

- name: Remove service files, binaries and data
  file:
    name: "{{ item }}"
    state: absent
  with_items:
    - /usr/local/bin/k3s
    - "{{ systemd_dir }}/k3s.service"
    - "{{ systemd_dir }}/k3s-node.service"
    - /etc/rancher/k3s
    - /var/lib/kubelet
    - /var/lib/rancher/k3s

- name: daemon_reload
  systemd:
    daemon_reload: yes

# - name: Remove iptables entries for kube's network policies
#   shell: 'iptables-save | grep -v KUBE-ROUTER | iptables-restore'

# - name: Remove iptables (v6) entries for kube's network policies
#   shell: 'ip6tables-save | grep -v KUBE-ROUTER | ip6tables-restore'

- name: Configure ufw for apiserver
  community.general.ufw:
    delete: true
    rule: allow
    port: '6443'
    interface: wg0
    direction: in
    proto: any

- name: Configure ufw for VXLAN
  community.general.ufw:
    delete: true
    rule: allow
    port: '8472'
    interface: wg0
    direction: in
    proto: any

- name: Configure ufw for kubelet metrics
  community.general.ufw:
    delete: true
    rule: allow
    port: '10250'
    interface: wg0
    direction: in
    proto: any

- name: Configure ufw for node-exporter metrics
  community.general.ufw:
    delete: true
    rule: allow
    port: '9100'
    interface: wg0
    direction: in
    proto: any

- name: Configure ufw for pods cidr
  community.general.ufw:
    delete: true
    rule: allow
    from: '10.11.0.0/16'
    to: any

- name: Configure ufw for services cidr
  community.general.ufw:
    delete: true
    rule: allow
    from: '10.12.0.0/16'
    to: any
